<a href="https://colab.research.google.com/github/Udynathcodes/Sheedx-Africa-Python-for-AI-ML/blob/main/Numpy_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np #alias
list1 = [2, 5, 3, 1]
array1 = np.array(list1)
print(array1)
print(type(array1))
print(type(list1))

[2 5 3 1]
<class 'numpy.ndarray'>
<class 'list'>


***Next array using np.zero()***

In [9]:
array2 = np.zeros(5)
print(array2)

[0. 0. 0. 0. 0.]


In [14]:
# np.arrange()
array3 = np.arange(5)
print("Using np.arrange(5)", array3)

array4 = np.arange(1, 9, 2)
print("Using np.arange()", array4)

Using np.arrange(5) [0 1 2 3 4]
Using np.arange() [1 3 5 7]


In [18]:
array5 = np.random.rand(5)
print(array5)

[0.26805007 0.54233277 0.7263549  0.92985284 0.02932177]


Empty Numpy array

In [19]:
array6 = np.empty(5)
print(array6)

[0. 0. 0. 0. 0.]


N-D **Array**

In [33]:
arr1 = np.array([[[1, 2, 3, 4],
                [9, 0 , 7, 9],
                 [5, 3, 22, 19]],

                 [[62, 58, 19, 32],
                 [90, 10, 39, 20],
                  [74, 32, 17, 83]]])
print(arr1)

[[[ 1  2  3  4]
  [ 9  0  7  9]
  [ 5  3 22 19]]

 [[62 58 19 32]
  [90 10 39 20]
  [74 32 17 83]]]


In [38]:
arr2 = np.zeros((2, 3))
print("2-D Array: ")
print(arr2)

arr3 = np.zeros((2, 3, 4))
print("3-D Array: ")
print(arr3)

2-D Array: 
[[0. 0. 0.]
 [0. 0. 0.]]
3-D Array: 
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


**Creating array with specified **value**

In [43]:
spe_val = np.full((2, 2), 10)
print("Array", spe_val)

Array [[10 10]
 [10 10]]


In [49]:
rand_gen = np.random.rand(2, 2)
print("Randomly generated array for 2D Array: ")
print(rand_gen)


rand_3D = np.random.rand(2, 2, 2)
print("Randomly generated array for 3D Array: ")
print(rand_3D)

Randomly generated array for 2D Array: 
[[0.39044707 0.90976714]
 [0.31800633 0.68646168]]
Randomly generated array for 3D Array: 
[[[0.9839688  0.2630807 ]
  [0.2837679  0.11473515]]

 [[0.75958833 0.57604837]
  [0.62182566 0.69817393]]]


Data types in Numpy Array

In [64]:
udy = np.array([2, 52, 4]) #creat an array of integer
un_dat = np.array([-2, -5, -4])
float1 = np.array([3.0, 4.2, 9.3])
comp = np.array([1+2j, 3+4j])
#check data types
print(udy.dtype)
print(un_dat.dtype)
print(float1.dtype)
print(comp.dtype)



int64
int64
float64
complex128


In [70]:
Udy2 = np.array([1, 4, 7], dtype=np.int32)
udy3 = np.array([1+2j, 2+3j, 3+2j], dtype='complex64')
print(udy3, udy3.dtype)
print(Udy2, Udy2.dtype)

[1.+2.j 2.+3.j 3.+2.j] complex64
[1 4 7] int32


**Type conversion**

In [71]:
type_con = np.array([2, 3, 4, 1])
#Convert int to float
float_con = type_con.astype('float')
print(type_con, type_con.dtype)
print(float_con, float_con.dtype)


[2 3 4 1] int64
[2. 3. 4. 1.] float64
