<a href="https://colab.research.google.com/github/Udynathcodes/Sheedx-Africa-Python-for-AI-ML/blob/main/Numpy_quiz_session.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
arr2 = np.array([[1, 2],[3, 4]])
print(arr2)

[[1 2]
 [3 4]]


In [ ]:
arr3 = np.zeros((3, 3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
rr

In [ ]:
arr4 = np.ones((4, 2))
print(arr4)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
arry = np.arange(10)
print(arry)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.linspace(0,1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr4 = np.random.rand(3,3)
print(arr4)

[[0.5207896  0.00624628 0.7906051 ]
 [0.13871092 0.1071452  0.42960116]
 [0.21897288 0.83585173 0.00587472]]


In [ ]:
glo = np.random.randint(1, 11, (3, 3))
print(glo)

[[6 7 3]
 [2 2 8]
 [2 2 4]]


In [ ]:
np.random.seed(42)
arr = np.random.rand(2,2)
print(arr)